import {mkdirSync,readdirSync,writeFileSync,readFileSync,existsSync,rmSync} from 'node:fs';
import {createHash} from 'node:crypto';import {basename,join,resolve} from 'node:path';import {extractSystemAnimatorGlb} from './lib/system-animator-glb';
const SOURCE='动画参考_glb',OUT=resolve('public/system-animator'),CATALOG='src/character/system-animator/catalog.generated.ts';
function scan(relative=''):string[]{return readdirSync(join(SOURCE,relative),{withFileTypes:true}).flatMap(e=>e.isDirectory()?scan(join(relative,e.name)):/\.glb$/i.test(e.name)?[join(relative,e.name).replaceAll('\\','/')]:[]).sort();}
function entry(filename:string){const stem=basename(filename).replace(/\.glb$/i,''),ascii=stem.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),hash=createHash('sha256').update(filename).digest('hex').slice(0,8);return{id:`xr-${ascii||'motion'}-${hash}`,label:stem.replaceAll('_',' ').trim(),file:stem,filename,category:'XR Animator',loop:false,ground:true,source:'system-animator-glb' as const};}
const entries=scan().map(entry);mkdirSync(OUT,{recursive:true});const expected=new Set(entries.map(e=>e.id+'.json'));expected.add('inventory.json');for(const name of readdirSync(OUT))if(name.endsWith('.json')&&!expected.has(name))rmSync(resolve(OUT,name));
const inventory=[],failures:string[]=[];
for(const def of entries){try{const bytes=readFileSync(resolve(SOURCE,def.filename)),sha=createHash('sha256').update(bytes).digest('hex'),path=resolve(OUT,def.id+'.json');let data;if(existsSync(path)){try{const cached=JSON.parse(readFileSync(path,'utf8'));if(cached.source?.sha256===sha&&cached.source?.extractorVersion==='system-animator-glb-v1')data=cached;}catch{}}if(!data){data=extractSystemAnimatorGlb(def.id,def.filename,SOURCE);writeFileSync(path,JSON.stringify(data));}inventory.push({...def,duration:data.duration,frames:data.times.length,fps:data.fps,bytes:Buffer.byteLength(JSON.stringify(data)),diagnostics:data.diagnostics});console.log(`GLB ${def.id}: ${data.times.length} frames / ${data.duration.toFixed(3)}s / ${def.filename}`);}catch(error){failures.push(def.filename+': '+String(error));console.error(failures.at(-1));}}
writeFileSync(CATALOG,'/** 自动生成；勿手写。来源：动画参考_glb/。 */\nexport const SYSTEM_ANIMATOR_CLIPS='+JSON.stringify(entries,null,2)+' as const;\n');writeFileSync(resolve(OUT,'inventory.json'),JSON.stringify({schema:'wanhu-system-animator-inventory-v1',totalFiles:entries.length,prepared:inventory.length,clips:inventory,failures},null,2));if(failures.length)throw new Error(`${failures.length} GLB 提取失败，详见 public/system-animator/inventory.json。`);console.log(`Prepared all ${inventory.length} SystemAnimator GLB clips.`);
