import{readFileSync as read,writeFileSync as write}from'node:fs';
function transform(p,fn){write(p,fn(read(p,'utf8')));}
transform('AGENTS.md',s=>s.replace('## 当前决定 · 衣冠工坊 V1','## 当前决定 · 衣冠工坊 V2').replace('README、Documentation/玩家角色自定义与服饰分期.md','README、Documentation/服装动画适配V2.md、Documentation/玩家角色自定义与服饰分期.md').replace('新长裳为双权重分片蒙皮','新长裳采用连续裤式分裳衣面，三级服饰LOD保持双权重').replace('目录 FBX、catalog.ts、review-mixamo.ts 独立矩阵必须一致。','prepare:mixamo递归扫描目录生成catalog.generated.ts；独立文件清单与全部动作review必须一致。').replace('check:mixamo/check:wardrobe','check:mixamo/check:wardrobe/check:tailoring').replace('新增衣服实现放 wardrobe/geometry.ts','新增衣面/LOD实现放 wardrobe/tailoring.ts，头饰发髻保留 wardrobe/geometry.ts')+'\n## V2专项门槛\n\n重点Pilot Flips Switches坐姿、射箭、慢跑与Snatch搬举压力测试；不能把源目录缺少的劳动动画称为已完成。Tailoring V2 Review同时跑闭合拓扑和独立三角贯穿诊断，输出真实多视角、全时间序列与视频。不要通过整段删腿、关闭检测或修改原FBX获得绿色。LOD只涉及服饰，不声称已做全人物LOD/GPU群体。人工复核状态写到服装动画适配V2.md。\n');
transform('Documentation/GPU骨骼动画迁移契约.md',s=>{
 const rest=s.slice(s.indexOf('---')+3);return '# GPU 骨骼动画迁移契约 · V2服饰 / FBX\n\n## V2衣面与LOD\n\n当前几何版本wanhu-tailoring-v2-continuous-1，衣面版本wanhu-tailoring-no-duplicate-lining-v2。原V1分层裙壳及隐藏大腿策略已替换：可见主衣面是完整连续裤式分裳，不重复绘制内裤/裙壳。原始body/joints保持。不可在Unity重新绘制一层完整裸体或继续套用V1删面表。\n\nLOD0/1/2为衣面过渡细分，当前原人体510tris、发式和装备仍保留；不是完整Crowd低模。LOD不属于Recipe；网格缓存键含LOD/几何版本，动画骨架语义不变。切换保持配方和相位。当前换网格仍重建演员/目标采样，最终共享缓存优化未实现。\n\n全部动态动作由FBX扫描目录生成；源文件SHA和extractorVersion决定缓存失效。inventory.json为包含clips/failures的对象。未知片段单次保持。新增抓举仅作搬举压力，不虚构工具或生产事件。\n\n'+rest;
});
transform('Documentation/玩家角色自定义与服饰分期.md',s=>'# 当前更新：服装动画适配V2\n\nV1的裙壳和静态搭接约定已退役。当前采用连续裤式分裳、三级衣物LOD和全FBX测试库；详细状态见[服装动画适配V2](服装动画适配V2.md)。以下V1内容是资源分期背景，不应覆盖V2生成/验收约束。\n\n'+s);
transform('Documentation/项目概览.md',s=>s.replace('衣冠工坊 V1','衣冠工坊 V2').replace('来自11个Mixamo FBX','来自实际目录扫描的Mixamo FBX（本次23个）').replace('四条Actions','五条Actions（新增Tailoring V2 Review）').replace('长摆是分片蒙皮非Cloth','当前写意衣面是连续裤式分裳非Cloth').replace('精确道具接触、Unity群体/LOD和性能均未完成','已提供三级服饰LOD手动对照；精确道具接触、Unity全人物/群体LOD和性能均未完成'));
transform('Documentation/GitHubActions截图验收规范.md',s=>s.replace('衣冠工坊 V1','衣冠工坊 V2').replace('## 四条流水线','## 五条流水线').replace('全11动作','全部扫描动作').replace('11 FBX新增服饰采样','全部FBX新增服饰采样').replace('| Wardrobe Review |','| Tailoring V2 Review | 三级服饰LOD、连续衣面/独立贯穿诊断、坐姿/射箭/搬举/慢跑完整时间序列和视频、动画库交互 |\n| Wardrobe Review |')+'\nV2采用连续裤式分裳，禁止引用V1的独立裙壳搭接检查证明V2通过。截图可另存隔离review证据分支供读取，不合入main运行资源，不部署任何站点。所有产物绑定testedSha。\n');
const pkg=JSON.parse(read('package.json','utf8'));pkg.scripts['check:intersections']='tsx scripts/check-tailoring-intersections.ts';write('package.json',JSON.stringify(pkg,null,2)+'\n');
transform('.github/workflows/tailoring-v2-review.yml',s=>s.replace('run: npm run check:tailoring','run: npm run check:tailoring\n      - name: Offline garment self-intersection regression\n        run: npm run check:intersections').replace('- name: Preview and browser review\n        run:','- name: Preview and browser review\n        if: always()\n        run:').replace('review-tailoring-v2/numeric.json','review-tailoring-v2/numeric.json\n            review-tailoring-v2/intersections.json'));
console.log('Documentation and independent intersection gate synchronized.');
