import{readFileSync as read,writeFileSync as write}from'node:fs';
// 仅处理源代码/文档，保留现有工作流文件和权限不变。
function transform(p,fn){write(p,fn(read(p,'utf8')));}
transform('AGENTS.md',s=>s.replace('## 当前决定 · 衣冠工坊 V1','## 当前决定 · 衣冠工坊 V2').replace('README、Documentation/玩家角色自定义与服饰分期.md','README、Documentation/服装动画适配V2.md、Documentation/玩家角色自定义与服饰分期.md').replace('新长裳为双权重分片蒙皮','新长裳采用连续裤式分裳衣面，三级服饰LOD保持双权重').replace('目录 FBX、catalog.ts、review-mixamo.ts 独立矩阵必须一致。','prepare:mixamo扫描目录生成catalog.generated.ts；独立文件清单与全动作review一致。').replace('check:mixamo/check:wardrobe','check:mixamo/check:wardrobe/check:tailoring').replace('新增衣服实现放 wardrobe/geometry.ts','新增衣面/LOD实现放 wardrobe/tailoring.ts，头饰发髻保留 wardrobe/geometry.ts')+'\n## V2门槛\n坐姿拨开关、射箭、慢跑、抓举压力测试为重点。Tailoring V2需闭合拓扑及离线三角贯穿诊断；数字通过不代表视觉通过。LOD仅服饰，不宣称全人物Crowd。实际状态见服装动画适配V2.md。\n');
const notice='> V2更新：当前采用连续裤式分裳，原V1双层裙壳/隐藏大腿策略已退役。LOD0/1/2仅衣面细分，原20骨骼/510tris身体保留。缓存必须区分LOD、wanhu-tailoring-v2-continuous-1和wanhu-tailoring-no-duplicate-lining-v2。全FBX自动扫描（本次23）；inventory.json包含clips/failures。后文V1阶段描述仅作历史背景，V2实现和验收以[服装动画适配V2](服装动画适配V2.md)为准。\n\n';
for(const p of ['Documentation/GPU骨骼动画迁移契约.md','Documentation/玩家角色自定义与服饰分期.md'])transform(p,s=>notice+s);
transform('Documentation/项目概览.md',s=>s.replace('衣冠工坊 V1','衣冠工坊 V2').replace('来自11个Mixamo FBX','来自真实目录扫描的Mixamo FBX（本次23）').replace('四条Actions','五条Actions（新增Tailoring V2 Review）').replace('长摆是分片蒙皮非Cloth','当前衣面是连续裤式分裳非Cloth').replace('Unity群体/LOD和性能均未完成','Unity全人物/群体LOD和性能均未完成；已提供三级服饰LOD手动对照'));
transform('Documentation/GitHubActions截图验收规范.md',s=>s.replace('衣冠工坊 V1','衣冠工坊 V2').replace('## 四条流水线','## 五条流水线').replace('全11动作','全部扫描动作').replace('11 FBX新增服饰采样','全部FBX新增服饰采样').replace('| Wardrobe Review |','| Tailoring V2 Review | 连续衣面/独立贯穿、三级LOD、坐姿/射箭/搬举/慢跑全时间序列和动作库交互 |\n| Wardrobe Review |')+'\n实际截图可另存隔离review证据分支，不合入main资源，不部署网站。所有产物绑定testedSha，不把自动化生成视为实际审图。\n');
const pkg=JSON.parse(read('package.json','utf8'));pkg.scripts['check:tailoring']='tsx scripts/check-tailoring-v2.ts && tsx scripts/check-tailoring-intersections.ts';pkg.scripts['check:intersections']='tsx scripts/check-tailoring-intersections.ts';write('package.json',JSON.stringify(pkg,null,2)+'\n');
console.log('Source/documentation validation updated; no workflow changes.');
