import {AnimationBrowser} from './character/mixamo/AnimationBrowser';
import { useState, useCallback, useRef, useEffect } from 'react';
import { MIXAMO_CLIPS,isMixamoId,mixamoDefinition,type MixamoSelection } from './character/mixamo/catalog';
import { CharacterViewport, type Stats, type View, type Display, type PlaybackStatus } from './scene/CharacterViewport';
import { BODY_TYPES, HAIR_STYLE_IDS, PRESET_IDS, applyPreset, createRecipe, patchSlots, type Recipe, type Outfit, type CharacterSlots, type GarmentDyes } from './character/v3/types';
import { WARDROBE_LOOKS, DYE_PALETTES, SLOT_OPTIONS, SLOT_LABELS, HAIR_NAMES, applyLook, randomizeLook, parseRecipeFile, type RandomLock } from './character/wardrobe/catalog';
import { garmentColors } from './character/wardrobe/geometry';
import { LookGlyph } from './character/wardrobe/LookGlyph';

const qs=new URLSearchParams(location.search),review=qs.has('review'),STORAGE_KEY='wanhu.character.wardrobe.v5';
function enumQuery<T extends string>(key:string,allowed:readonly T[],fallback:T):T{const v=qs.get(key) as T|null;return v&&allowed.includes(v)?v:fallback;}
function initialPhase(){const n=Number(qs.get('phase')??0);return Number.isFinite(n)?Math.max(0,Math.min(1,n)):0;}
function initialRecipe():Recipe {
  const bodyType=enumQuery('bodyType',BODY_TYPES,'male');
  let r=createRecipe({bodyType});
  // 仅保留当前明确入口；旧身材/装备/LOD URL 参数不参与解析。
  if(qs.has('preset'))r=applyPreset(r,enumQuery('preset',PRESET_IDS,'farmer'));
  else r=applyLook(r,qs.get('look')??'town-'+bodyType);
  const slots:Record<string,string>={};for(const key of Object.keys(SLOT_OPTIONS)){const v=qs.get(key);if(v)slots[key]=v;}
  if(Object.keys(slots).length)r=createRecipe({...r,slots:{...r.slots,...slots}});
  return r;
}
function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function sameAppearance(a:Recipe,b:Recipe){return JSON.stringify([a.slots,a.dyes,a.hairStyle])===JSON.stringify([b.slots,b.dyes,b.hairStyle]);}
export default function App(){

  // review 链接保持原来的 FBX 默认以进行独立回归；玩家换装默认静态绑定。
  const [mixamo,setMixamo]=useState<MixamoSelection>(()=>qs.get('pose')==='bind'?'none':isMixamoId(qs.get('mixamo'))?qs.get('mixamo') as MixamoSelection:review?'jogging':'none');
  const [recipe,setRecipe]=useState<Recipe>(initialRecipe),[past,setPast]=useState<Recipe[]>([]);
  const [allLooks,setAllLooks]=useState(false),[locks,setLocks]=useState<RandomLock[]>([]),[seed,setSeed]=useState('1');
  const [notice,setNotice]=useState(''),[importError,setImportError]=useState('');const fileRef=useRef<HTMLInputElement>(null);
  const [compareSource,setCompareSource]=useState(qs.get('compare')==='1'),[headAxes,setHeadAxes]=useState(qs.get('headAxes')==='1');
  const [restart,setRestart]=useState(0),[playback,setPlayback]=useState<PlaybackStatus>({phase:initialPhase(),stage:'',finished:false});
  const [playing,setPlaying]=useState(!qs.has('paused')&&(review||qs.has('mixamo'))),[speed,setSpeed]=useState(1),[phase,setPhase]=useState(initialPhase);
  const [view,setView]=useState<View>(enumQuery('view',['free','front','side','back','top','three'] as const,'front')),[viewRevision,setViewRevision]=useState(0),[orthographic,setOrthographic]=useState(true);
  const [display,setDisplay]=useState<Display>(enumQuery('display',['beauty','cage','triangles','clay'] as const,'beauty'));
  const [skeleton,setSkeleton]=useState(false),[grid,setGrid]=useState(false),[error,setError]=useState(''),[stats,setStats]=useState<Stats|null>(null);
  const updatePlayback=useCallback((v:PlaybackStatus)=>{setPlayback(v);if(v.finished)setPlaying(false);},[]);
  const recipeRef=useRef(recipe);recipeRef.current=recipe;
  const edit=(fn:(r:Recipe)=>Recipe)=>{const current=recipeRef.current,next=fn(current);if(JSON.stringify(next)===JSON.stringify(current))return;recipeRef.current=next;setPast(p=>[...p.slice(-29),current]);setRecipe(next);};
  const patch=(value:Partial<Recipe>)=>edit(r=>createRecipe({...r,...value}));
  const patchSlot=<K extends keyof CharacterSlots>(slot:K,value:CharacterSlots[K])=>edit(r=>patchSlots(r,{[slot]:value} as Partial<CharacterSlots>));
  const selectMixamo=(id:MixamoSelection)=>{setMixamo(id);setPhase(0);setPlaying(id!=='none');setRestart(n=>n+1);};
  const selectView=(v:View)=>{setView(v);setViewRevision(n=>n+1);};
  const replay=()=>{setPhase(0);setRestart(n=>n+1);setPlaying(true);};
  const active=mixamo==='none'?null:mixamoDefinition(mixamo),ready=Boolean(playback.mixamo&&playback.mixamo.id===mixamo);
  const currentLook=WARDROBE_LOOKS.find(l=>sameAppearance(recipe,applyLook(recipe,l.id)));
  const toggleLock=(key:RandomLock)=>setLocks(current=>current.includes(key)?current.filter(k=>k!==key):[...current,key]);
  const randomize=()=>{const n=Number(seed);if(!Number.isFinite(n)||!Number.isInteger(n)||n<0||n>4294967295){setNotice('种子需为 0–4294967295 的整数。');return;}edit(r=>randomizeLook(r,n,locks));setNotice(`已按种子 ${n} 生成装扮，锁定项保持不变。`);setSeed(String((n+1)>>>0));};
  const save=()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(recipe));setNotice('已保存到此浏览器。');}catch{setNotice('浏览器存储不可用，请导出配方保存。');}};
  const restore=()=>{try{const text=localStorage.getItem(STORAGE_KEY);if(!text){setNotice('此浏览器还没有保存的装扮。');return;}const next=parseRecipeFile(text);edit(()=>next);setNotice('已恢复保存的装扮。');}catch(e){setNotice('恢复失败：'+String(e));}};
  const importFile=async(file:File|undefined)=>{if(!file)return;try{if(file.size>32768)throw new Error('配方文件过大（最多 32 KB）。');const r=parseRecipeFile(await file.text());edit(()=>r);setImportError('');setNotice('已导入配方。');}catch(e){setImportError(e instanceof Error?e.message:String(e));}finally{if(fileRef.current)fileRef.current.value='';}};
  useEffect(()=>{if(!review)return;window.__WANHU_RECIPE__=()=>recipe;return()=>{delete window.__WANHU_RECIPE__;};},[recipe]);
  return <main className="studio wardrobe-studio">
    <header className="topbar"><div className="brand-mark">工</div><div><p className="eyebrow">WANHU / CHARACTER ATELIER</p><h1>万户 · 衣冠工坊</h1></div><div className="header-right"><span className="version">固定基模 · V5</span><button className="ghost" disabled={!past.length} onClick={()=>{const previous=past.at(-1);if(previous){setRecipe(previous);setPast(p=>p.slice(0,-1));}}}>撤销</button><button className="ghost" onClick={()=>fileRef.current?.click()}>导入配方</button><button className="primary-button" onClick={()=>download(`wanhu-${recipe.bodyType}-recipe.json`,recipe)}>导出配方</button><input ref={fileRef} aria-label="导入配方文件" type="file" accept=".json,application/json" hidden onChange={e=>void importFile(e.target.files?.[0])}/></div></header>
    <div className="workspace">
      <aside className="sidebar look-sidebar">
        <section aria-label="居民体型"><div className="section-title"><h2>你的角色</h2><span>01 / BODY</span></div><div className="display-grid">{BODY_TYPES.map(type=><button key={type} data-testid={'body-type-'+type} aria-pressed={recipe.bodyType===type} className={recipe.bodyType===type?'active':''} onClick={()=>patch({bodyType:type})}>{type==='female'?'女性':'男性'}</button>)}</div><p className="hint">固定男女基模，切换保留装扮和动画相位。</p></section>
        <section className="look-section"><div className="section-title"><h2>搭配灵感</h2><button className="text-button" aria-pressed={allLooks} onClick={()=>setAllLooks(v=>!v)}>{allLooks?'推荐款式':'全部 8 款'}</button></div><p className="hint">预设只是起点，每件都可自由替换。</p><div className="look-grid">{WARDROBE_LOOKS.filter(l=>allLooks||l.suggestedBody===recipe.bodyType).map(l=><button key={l.id} data-testid={'look-'+l.id} aria-pressed={currentLook?.id===l.id} className={'look-card '+(currentLook?.id===l.id?'selected':'')} onClick={()=>edit(r=>applyLook(r,l.id))}><span className="look-illustration"><LookGlyph look={l}/><span>{l.family}</span></span><strong>{l.name}</strong><small>{l.description}</small></button>)}</div></section>
        <details className="classic-presets" open={review}><summary>基础搭配</summary><div className="classic-grid">{([['farmer','农户'],['guard','卫兵'],['archer','弓手'],['body','基础人体']] as [Outfit,string][]).map(([id,label])=><button key={id} onClick={()=>edit(r=>applyPreset(r,id))}>{label}</button>)}</div></details>
        <section className="spaced"><div className="section-title"><h2>探索组合</h2><span>SEED</span></div><div className="seed-row"><input aria-label="搭配种子" type="number" min="0" max="4294967295" value={seed} onChange={e=>setSeed(e.target.value)}/><button className="primary-button" onClick={randomize}>随机搭配</button></div><p className="hint">相同种子可复现；只改搭配，不改男女基模。</p><div className="display-grid"><button onClick={save}>保存装扮</button><button onClick={restore}>恢复装扮</button></div></section>
      </aside>
      <section className="stage" aria-label="人物预览">
        <div className="stage-heading"><p className="eyebrow">DRESS YOUR CHARACTER</p><h2>{currentLook?.name??'自定义装扮'}</h2><p>{recipe.bodyType==='female'?'女性':'男性'} · 标准低模 · {active?.label??'静态试衣'}</p></div>
        <div className="camera-bar">{([['free','自由'],['front','正面'],['side','侧面'],['back','背面'],['three','三视图']] as [View,string][]).map(([v,label])=><button key={v} className={view===v?'active':''} onClick={()=>selectView(v)}>{label}</button>)}<button disabled={view==='three'} onClick={()=>setOrthographic(v=>!v)}>{orthographic?'正交':'透视'}</button><button aria-label="保存截图" onClick={()=>window.__WANHU_CAPTURE__?.()}>截图</button></div>
        {error?<div role="alert" className="error-panel">{error}<button onClick={()=>location.reload()}>重新加载</button></div>:<CharacterViewport options={{recipe,mixamo,compareSource,headAxes,restart,playing,speed,phase,view,viewRevision,orthographic,display,skeleton,grid}} onPlayback={updatePlayback} onStats={setStats} onError={setError}/>}
        {mixamo!=='none'&&compareSource&&view!=='three'&&<div className="mixamo-compare-labels"><span>源动画骨架</span><span>当前角色</span></div>}
        {view==='three'&&<div className="three-labels"><span>正面</span><span>侧面</span><span>背面</span></div>}
        <div className="stage-caption"><span>拖动旋转 · 滚轮缩放</span><span data-testid="triangles">{stats?.triangles??'—'} tris · {stats?.bones??'—'} 骨骼</span></div>
        <section className="motion-panel"><div className="motion-head"><span className="eyebrow">试衣 / 动作</span><select aria-label="试衣动画" value={mixamo} onChange={e=>selectMixamo(e.target.value as MixamoSelection)}><option value="none">静态绑定</option>{MIXAMO_CLIPS.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select><div className="speed"><label htmlFor="speed">速度</label><select id="speed" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[.25,.5,1,1.5,2].map(v=><option key={v} value={v}>{v}×</option>)}</select></div></div><div className="motion-actions"><button className={!active?'active':''} aria-pressed={!active} onClick={()=>selectMixamo('none')}>绑定姿态（静态）</button><button disabled={!ready} onClick={replay}>重播外部动作</button><button disabled={!ready} className="play-button" aria-label={playing?'暂停':'播放'} onClick={()=>playback.finished?replay():setPlaying(v=>!v)}>{playing?'Ⅱ 暂停':'▶ 播放'}</button></div><div className="mixamo-status" data-testid="mixamo-status" role="status"><span>{!active?'静态试衣 · 选择 FBX 检查衣物变形':playback.loading?'正在载入并烘焙…':playback.loadError??(ready?`${playback.mixamo!.duration.toFixed(2)} 秒 · ${playback.mixamo!.loop?'循环':'单次，结束保持'}`:'准备动画')}</span>{playback.loadError&&<button onClick={replay}>重试加载</button>}</div><div className="frame-controls">{([-1,1] as const).map(delta=><button key={delta} disabled={!ready} onClick={()=>{const duration=playback.mixamo?.duration??1;const next=Math.max(0,Math.min(1,playback.phase+delta/(30*duration)));setPlaying(false);setPhase(next);setPlayback(p=>({...p,phase:next}));}}>{delta<0?'上一帧':'下一帧'}</button>)}</div><label className="timeline"><span>进度</span><input aria-label="动画进度" type="range" disabled={!ready} min="0" max="1" step=".001" value={playback.phase} onChange={e=>{const n=+e.target.value;setPlaying(false);setPhase(n);setPlayback(p=>({...p,phase:n}));}}/><output>{Math.round(playback.phase*100)}%</output></label></section>
        {(notice||importError)&&<div className={'studio-notice '+(importError?'notice-error':'')} role="status">{importError||notice}<button aria-label="关闭提示" onClick={()=>{setNotice('');setImportError('');}}>×</button></div>}
      </section>
      <aside className="sidebar wardrobe-sidebar">
        <div className="section-title"><h2>衣冠部件</h2><span>02 / WARDROBE</span></div><p className="hint">勾选锁定项，仅影响随机搭配。</p><div className="slot-grid">{(['top','bottom','headwear','shoes'] as const).map(key=><div className="slot-item" key={key}><label className="slot-row"><span>{SLOT_LABELS[key]}</span><select aria-label={SLOT_LABELS[key]} value={recipe.slots[key]} onChange={e=>patchSlot(key,e.target.value as CharacterSlots[typeof key])}>{SLOT_OPTIONS[key].map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="lock-control"><input aria-label={'锁定'+SLOT_LABELS[key]} type="checkbox" checked={locks.includes(key)} onChange={()=>toggleLock(key)}/>锁定</label></div>)}</div>
        <section className="spaced"><div className="section-title"><h2>染色</h2><label className="lock-control"><input aria-label="锁定染色" type="checkbox" checked={locks.includes('dyes')} onChange={()=>toggleLock('dyes')}/>锁定</label></div><div className="dye-palettes">{DYE_PALETTES.map(({name,...colors})=><button key={name} aria-label={'色组'+name} title={name} onClick={()=>patch({dyes:colors})}>{Object.values(colors).map((color,i)=><span key={i} style={{background:color}}/>)}</button>)}</div><div className="dye-controls">{([['primary','主布'],['secondary','下装 / 内衬'],['accent','缘边 / 腰带']] as [keyof GarmentDyes,string][]).map(([key,label])=><label key={key}><span>{label}</span><input aria-label={label+'颜色'} type="color" value={garmentColors(recipe)[key]} onChange={e=>patch({dyes:{...garmentColors(recipe),[key]:e.target.value}})}/></label>)}</div><p className="hint">新衣支持三色分区；原有兵装保留固定色。</p></section>
        <section className="spaced"><div className="section-title"><h2>发式</h2><label className="lock-control"><input aria-label="锁定发型" type="checkbox" checked={locks.includes('hairStyle')} onChange={()=>toggleLock('hairStyle')}/>锁定</label></div><label className="slot-row"><span>发型</span><select aria-label="发型" value={recipe.hairStyle} onChange={e=>patch({hairStyle:e.target.value as Recipe['hairStyle']})}>{HAIR_STYLE_IDS.map(id=><option key={id} value={id}>{HAIR_NAMES[id]}</option>)}</select></label><label className="hair-color"><span>发色</span><input aria-label="发色" type="color" value={recipe.hairColor} onChange={e=>patch({hairColor:e.target.value})}/></label><p className="hint">帽冠遮蔽发髻，取下后自动恢复。</p></section>
        <details className="spaced" open={review}><summary>随身装备</summary><div className="slot-grid">{(['back','leftHand','rightHand'] as const).map(key=><div className="slot-item" key={key}><label className="slot-row"><span>{SLOT_LABELS[key]}</span><select aria-label={SLOT_LABELS[key]} value={recipe.slots[key]} onChange={e=>patchSlot(key,e.target.value as CharacterSlots[typeof key])}>{SLOT_OPTIONS[key].map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label className="lock-control"><input aria-label={'锁定'+SLOT_LABELS[key]} type="checkbox" checked={locks.includes(key)} onChange={()=>toggleLock(key)}/>锁定</label></div>)}</div><button className="clear-equipment" onClick={()=>edit(r=>patchSlots(r,{back:'none',leftHand:'none',rightHand:'none'}))}>清空随身装备</button></details>
        <AnimationBrowser value={mixamo} onSelect={selectMixamo}/><details className="spaced inspect-tools" open={review}><summary>动画与结构检查</summary><div className="display-grid">{([['beauty','着色'],['clay','素模'],['cage','结构布线'],['triangles','三角网格']] as [Display,string][]).map(([id,label])=><button key={id} className={display===id?'active':''} onClick={()=>setDisplay(id)}>{label}</button>)}</div><label className="switch-row">骨骼叠加<input type="checkbox" checked={skeleton} onChange={e=>setSkeleton(e.target.checked)}/></label><label className="switch-row">地面网格<input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/></label><label className="switch-row">源骨架同步对照<input aria-label="源骨架同步对照" type="checkbox" checked={compareSource} onChange={e=>setCompareSource(e.target.checked)}/></label><label className="switch-row">头部朝向检查<input aria-label="头部朝向检查" type="checkbox" checked={headAxes} onChange={e=>setHeadAxes(e.target.checked)}/></label><button className="clear-equipment" disabled={!ready} onClick={()=>{const d=window.__WANHU_EXPORT_MOTION__?.();if(d)download(`wanhu-${recipe.bodyType}-${mixamo}-target-motion.json`,d);}}>导出目标骨架动画 JSON</button><p className="hint">FBX 仅提供人体动作；长摆极端动作与精确道具接触仍需后续制作。</p></details>
      </aside>
    </div>
  </main>;
}
declare global {interface Window {__WANHU_RECIPE__?:()=>Recipe}}
